apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"https":"HTTPS"}'
  name: {{ include "secoda.fullname" . }}
  labels:
    {{- include "secoda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    {{- include "secoda.selectorLabels" . | nindent 4 }}